version: '3'

services:
  mysql:
    build:
      context: ./backend/db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_net
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "localhost"
      MYSQL_PASSWORD: "pass"
      MYSQL_HOST : "mysql"
      MYSQL_DATABASE: "proj_db"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: ["--init-file", "/docker-entrypoint-initdb.d/001-script.sql"]


  app:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    networks:
      - app_net
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
  
networks:
  app_net: